
---

connectors:
  - sqs_queue_name: "your-queue-name"
    slack_hook_url: "https://hooks.slack.com/services/123456789/QWERTYUIO/ASDFGHJKZXCVBNM1234567890"
    delete_msg: false

dns_worker_threads: 1
tokio_core_threads: 2
